# Generated by Django 4.0 on 2022-02-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='author_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
