# Generated by Django 4.0 on 2022-02-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensen', '0002_blogpage_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='blog_body',
            field=models.TextField(max_length=200000),
        ),
    ]
