# Generated by Django 4.0 on 2022-02-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensen', '0003_alter_blogpage_blog_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='author_name',
            field=models.CharField(default='Not Provided..', max_length=100),
        ),
    ]
