# Generated by Django 4.0 on 2022-02-10 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensen', '0004_alter_blogpage_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='author_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensen.author'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='author_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
