# Generated by Django 4.0 on 2022-02-10 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensen', '0005_blogpage_author_user_alter_blogpage_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='author_user',
        ),
    ]
