# Generated by Django 4.0 on 2022-02-10 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensen', '0006_remove_blogpage_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='author_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensen.author'),
        ),
    ]
